name: Deploy to GitHub Pages

on:
  push:
    branches: [master]

jobs:
  deploy-to-github-pages:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '7.0'
          dotnet-quality: # optional
          global-json-file: # optional
          source-url: # optional
          owner: # optional
          config-file: # optional
          cache: # optional
          cache-dependency-path: # optional

      - name: Publish .NET Core Project
        run: dotnet publish "GitTest_BlazorShop/GitTest_BlazorShop.csproj" -c Release -o release --nologo
